[package]
name = "domains"
version = "0.1.0"
edition = "2024"

[dependencies]
app_helpers.workspace = true
axum.workspace = true
chrono.workspace = true
secrecy.workspace = true
serde.workspace = true
utility-types.workspace = true
uuid.workspace = true
sqlx.workspace = true
welds.workspace = true