[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy.workspace = true
secrecy.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
